//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscriptionEntity
    {
        public int Id { get; set; }
        public int IdParticipant { get; set; }
        public int IdCourse { get; set; }
        public int IdSuiviInscription { get; set; }
        public Nullable<int> NumClassement { get; set; }
        public Nullable<System.TimeSpan> Temps { get; set; }
    
        public virtual RaceEntity Course { get; set; }
        public virtual ContributorEntity Participant { get; set; }
        public virtual SuiviInscription SuiviInscription { get; set; }
    }
}
